import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./Providers";
import { ThemeProvider } from "next-themes";

import Providers from "./provider";

import { Lexend_Deca } from "next/font/google";
import EmailVerificationToast from "@/components/toast/EmailVerification";

const lexendDeca = Lexend_Deca({
  subsets: ["latin"],
  weight: ["400", "700"], // ใช้เฉพาะน้ำหนักที่จำเป็น
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lexendDeca.className} suppressHydrationWarning>
      <Providers>
        <AuthProvider>
          <body className="bg-gray-50 dark:bg-gray-950 dark:text-gray-100">
            <ThemeProvider attribute="class" enableSystem defaultTheme="system">
              <Toaster position="top-center" />
              <EmailVerificationToast /> {/* 👈 ตรวจ session + toast ที่นี่ */}
              {children}
            </ThemeProvider>
          </body>
        </AuthProvider>
      </Providers>
    </html>
  );
}
