import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./Providers";
import { ThemeProvider } from "next-themes";

import Providers from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <AuthProvider>
          <body>
            <ThemeProvider attribute="class" enableSystem defaultTheme="system">
              <Toaster position="top-center" />
              {children}
            </ThemeProvider>
          </body>
        </AuthProvider>
      </Providers>
    </html>
  );
}
