import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./Providers";

import Providers from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <AuthProvider>
          <body>
            <Toaster position="top-center" />
            {children}
          </body>
        </AuthProvider>
      </Providers>
    </html>
  );
}
